### ISSUE TITLE
f-string-parser: Fix test_format_specifier_expressions

### ISSUE THREAD

**Issue by pablogsal** [we-like-parsers/cpython#153]
In `test_fstring` the test `test_format_specifier_expressions` is failing with:

```
ERROR: test_format_specifier_expressions (test.test_fstring.TestCase) (str="f'result: {value:{width:{0}}.{precision:1}}'")\n----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/pablogsal/github/python/f-string-grammar/Lib/test/test_fstring.py", line 33, in assertAllRaise
    eval(str)
    ^^^^^^^^^
  File "<string>", line 1, in <module>
NameError: name 'value' is not defined
```

**Comment by isidentical** [comment]
Not much to fix for the above case, since it is due to the nested expression depth which we removed;
https://github.com/python/cpython/blob/c96d1546b11b4c282a7e21737cb1f5d16349656d/Parser/string_parser.c#L551-L556

**Comment by pablogsal** [comment]
Then we need to change the tests
